config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'

  resources :prospects, only: [:index]
  resources :imponeders, only: [:index]
  resources :musterrs, only: [:index]
  resources :konks, only: [:index]
  resources :pract_sous, only: [:index]
  resources :gadois, only: [:index]
  resources :mwbes, only: [:index]
  resources :tuna_permits, only: [:index] 
  resources :mtech_suppliers, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gadoi.rb
class Gadoi < ActiveRecord::Base

   self.per_page = 100

   def address
     [address1, address2].join(',')
   end
   def cityz
     [city,zip].join(',')
   end
   def contact
     [fname,lname].join(' ')
   end

end

app/models/imponeder.rb
class Imponeder < ActiveRecord::Base
end

app/models/konk.rb
class Konk < ActiveRecord::Base

  def address
    [street, plz, canton, city].join(' ')
  end
  def contact
    [fname, lname].join(' ')
  end

end

app/models/mtech_supplier.rb
class MtechSupplier < ApplicationRecord

   def address1
      [street, town].join(' ')
   end
   def cityz
     [province, postcode].join(' ')
   end

end

app/models/musterr.rb
class Musterr < ApplicationRecord

  def address
    [street, plz, canton, city].join(' ')
  end
  def contact
    [fname, lname].join(' ')
  end

end

app/models/mwbe.rb
class Mwbe < ActiveRecord::Base
 

  def cityz
   [city,zip].join(',')
  end

end

app/models/pract_sou.rb
class PractSou < ActiveRecord::Base

  def address1
    [address, town].join(' ')
  end
  def country1
    [region, country].join(',')
  end
  def contact
    [fname, lname].join(' ')
  end

end

app/models/prospect.rb
class Prospect < ActiveRecord::Base
end

app/models/tuna_permit.rb
class TunaPermit < ActiveRecord::Base

  self.per_page = 100

  def address
   [address1,address2].join(', ')
  end
  def cityz
   [city,zip].join(', ')
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/gadois_controller.rb
class GadoisController < ApplicationController

  def index
    @gadois = Gadoi.paginate(:page => params[:page])
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

end

app/controllers/konks_controller.rb
class KonksController < ApplicationController

  def index
    @konks = Konk.all
  end

end

app/controllers/musterrs_controller.rb
class MusterrsController < ApplicationController

   def index
     @musterrs = Musterr.all
   end

end

app/controllers/mwbes_controller.rb
class MwbesController < ApplicationController

  def index
    @mwbes = Mwbe.all
  end

end

app/controllers/prospects_controller.rb
class ProspectsController < ApplicationController

  def index
    @prospects = Prospect.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/imponeders_helper.rb
module ImponedersHelper
end

app/helpers/musterrs_helper.rb
module MusterrsHelper
end

app/helpers/prospects_helper.rb
module ProspectsHelper
end

app/views/home/index.html.erb
<p>Welcome <%= current_user.email %> </p>

<div class="row">
 <div class="col-md-3">
   <%= image_tag 'adsmith-5.jpg', class: 'kmain' %>
 </div>
   <div class="col-md-9">
    <div class="row">
   <div class="col-md-4">
    <p>EUROPE</p>
    <div class="nav_item">
     <%=  link_to "Pros Eu", prospects_path, class:"btn btn-lg btn-success" %> 
      <h5>Some 2k plus EU Postal addresses</h5>
    </div>   
    <br/>
    <div class="nav_item">
     <%= link_to "Importers", imponeders_path, class:"btn btn-lg btn-success" %>
      <h5>Some 2k5 Dutch Postal addresses</h5>
    </div>
    <br/>    
    <div class="nav_item">
     <%= link_to "Musterr", musterrs_path, class:"btn btn-lg btn-danger" %>
      <h5>Some 1k Switz Postal addresses</h5>
    </div>
    <br/>
        <div class="nav_item">
     <%= link_to "Konks", konks_path, class:"btn btn-lg btn-danger" %>
      <h5>Some 700 Switz Postal addresses. Not really too sure</h5>
    </div>
    <br/>
   </div>

   <div class="col-md-4">
    <p>AMERICAS</p>
    <div class="nav_item">
     <%=  link_to "Gadoi", gadois_path, class:"btn btn-lg btn-success" %> 
      <h5>Some 97k plus American postal addresses</h5>
    </div>
     <br/>
    <div class="nav_item">
     <%=  link_to "Mweb", mwbes_path, class:"btn btn-lg btn-success" %> 
     <h5>Some 3k plus postal addresses</h5>
    </div>
    <br/>
    <div class="nav_item">
     <%=  link_to "Tuna Permit", tuna_permits_path, class:"btn btn-lg btn-info" %>
     <h5>Some 5k plus postal addresses</h5>
    </div>
    <br/>
   </div>

   <div class="col-md-4">
    <p>WORLD</p>
    <div class="nav_item">
     <%=  link_to "Address", pract_sous_path, class:"btn btn-lg btn-success" %>
     <h5>Some 350 worldwide postal addresses</h5>
    </div>
    <br/>
    <div class="nav_item">
     <%=  link_to "MTech", mtech_suppliers_path, class:"btn btn-lg btn-danger" %>
     <h5>Some 400 Manure Managemnt Technology Supplier Contact worldwide</h5>
    </div>
    <br/> 
  </div>
 
    </div>
    </div>
</div>